version: "3.5"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "todo_user"
      MONGO_INITDB_ROOT_PASSWORD: "todo@123"
    ports:
      - "27017:27017"

  my_app:
    container_name: my-app-container
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8000:8000"
